# Generated by Django 2.2.4 on 2019-08-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='presentation_quality',
            field=models.CharField(default='blah', help_text='Did they present well? Did they do the things?', max_length=200),
            preserve_default=False,
        ),
    ]
