# Generated by Django 2.2.4 on 2019-08-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0002_auto_20190804_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something_one', models.CharField(max_length=200)),
                ('stg_two', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EngMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation_quality', models.CharField(help_text='Did they present well? Did they do the things?', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='VisualArtsMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
            bases=('steamify.shared',),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
