# Generated by Django 2.2.4 on 2019-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0003_auto_20190804_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='year_in_school',
            field=models.CharField(choices=[('F', 'Freshman'), ('S', 'Sophomore'), ('J', 'Junior'), ('SE', 'Senior')], default='F', max_length=2),
        ),
    ]
