# Generated by Django 2.2.4 on 2019-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0004_shared_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', max_length=2),
        ),
    ]
