# Generated by Django 2.2.4 on 2019-10-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0004_alloweddevice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddevice',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
