# Generated by Django 2.2.4 on 2019-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0005_auto_20190804_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1'),
        ),
    ]
