# Generated by Django 2.2.4 on 2019-08-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0008_engmiddle_shared_visualartsmiddle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engmiddle',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='stg_two',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='year_in_school',
        ),
    ]
