# Generated by Django 2.2.4 on 2019-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0009_auto_20190807_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engmiddle',
            name='presentation_quality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Did they present well? Did they do the things?'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
