# Generated by Django 2.2.4 on 2019-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0010_auto_20190818_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='something_one',
        ),
        migrations.AddField(
            model_name='shared',
            name='something_shared',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Did they do somethign well that involes all competitions?'),
            preserve_default=False,
        ),
    ]
