# Generated by Django 2.2.4 on 2019-08-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0011_auto_20190818_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualArtsElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('artistic_artsyness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Are they artsy? OR Fartsy?')),
            ],
            bases=('steamify.shared',),
        ),
    ]
