# Generated by Django 2.2.5 on 2019-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0013_shared_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('dotted_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
