# Generated by Django 2.2.4 on 2019-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0014_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engmiddle',
            name='presentation_quality',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='something_shared',
        ),
        migrations.AddField(
            model_name='engmiddle',
            name='design_notebook',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], default=4, help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.\uf0b7Design process somewhat chronicled.\uf0b7Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engmiddle',
            name='engineering_design_prototype_working_model',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], default=4, help_text='<ul><li>The operation and design of the prototype somewhat fulfill the challenge, but is unclear in some aspects.</li></ul>', verbose_name='Engineering Design/Prototype/Working Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engmiddle',
            name='presentation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], default=4, help_text='<ul><li>Presentation demonstrates understanding of the material.</li>\n<li>Presenters facilitate engaging discussion regarding challenge expectations.</li>\n<li>Presenters explain their research concerning the CO2 device as it relates to environmental sustainability.</li>\n<li>The purpose of the design is clear, realistic, and presenters share how it may be scaled up.</li>\n<li>Most students have an explicit part in either the explanation or demonstration of the design process regarding the prototype; however, one or two may function as support.</li></ul>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualartselem',
            name='artistic_artsyness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], help_text='Are they artsy? OR Fartsy?'),
        ),
    ]
