# Generated by Django 2.2.4 on 2019-09-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0015_auto_20190928_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='engmiddle',
            name='engineering_statement',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], default=4, help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engmiddle',
            name='design_notebook',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3 (meets)'), (4, '4'), (5, '5 (exceeds)')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>'),
        ),
    ]
