# Generated by Django 2.2.4 on 2019-10-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0017_auto_20191007_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeroMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DanceElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DanceMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DebateMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='EngElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='RocketMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='SpokenElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='SpokenMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='TheaterElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='TheaterMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
            ],
            bases=('steamify.shared',),
        ),
    ]
