# Generated by Django 2.2.4 on 2019-10-08 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0019_shared_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shared',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
