# Generated by Django 2.2.4 on 2019-10-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0020_auto_20191008_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spont',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('specific_to_spontaneous', models.IntegerField(choices=[(1, '1 (lowest)'), (2, '2'), (3, '3 (meets described standards)'), (4, '4'), (5, '5 (exceeds described standards)')], help_text='<ul><li>Words about things.</li>\n<li>This also says this.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.AlterField(
            model_name='visualartselem',
            name='artistic_artsyness',
            field=models.IntegerField(choices=[(1, '1 (lowest)'), (2, '2'), (3, '3 (meets described standards)'), (4, '4'), (5, '5 (exceeds described standards)')], help_text='<ul><li>Are they artsy? OR Fartsy?</li></ul>'),
        ),
    ]
