# Generated by Django 2.2.4 on 2019-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamify', '0021_auto_20191009_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualartsmiddle',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='visualartsmiddle',
            name='votes',
        ),
        migrations.AlterField(
            model_name='engmiddle',
            name='design_notebook',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>'),
        ),
        migrations.AlterField(
            model_name='engmiddle',
            name='engineering_design_prototype_working_model',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The operation and design of the prototype somewhat fulfill the challenge, but is unclear in some aspects.</li></ul>', verbose_name='Engineering Design/Prototype/Working Model'),
        ),
        migrations.AlterField(
            model_name='engmiddle',
            name='engineering_statement',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>'),
        ),
        migrations.AlterField(
            model_name='engmiddle',
            name='presentation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Presentation demonstrates understanding of the material.</li>\n<li>Presenters facilitate engaging discussion regarding challenge expectations.</li>\n<li>Presenters explain their research concerning the CO2 device as it relates to environmental sustainability.</li>\n<li>The purpose of the design is clear, realistic, and presenters share how it may be scaled up.</li>\n<li>Most students have an explicit part in either the explanation or demonstration of the design process regarding the prototype; however, one or two may function as support.</li></ul>'),
        ),
        migrations.AlterField(
            model_name='spont',
            name='specific_to_spontaneous',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Words about things.</li>\n<li>This also says this.</li></ul>'),
        ),
        migrations.AlterField(
            model_name='visualartselem',
            name='artistic_artsyness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Are they artsy? OR Fartsy?</li></ul>'),
        ),
    ]
