# Generated by Django 2.2.4 on 2019-10-18 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('dotted_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('school_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AeroMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The machine may be slightly damaged upon landing.</li>\n<li>The machine launches as one complete unit.</li>\n<li>The design includes aesthetic improvements, however some may be distracting or random.</li>\n<li>Most students have an explicit part in either the launching or explanation of the design process; however, one or two may function as support.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('fulfillment_of_problem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The execution of the launching and the design of the rocket fulfill all but 1 challenge requirement.</li>\n<li>The flight time is in the middle third of all teams.</li></ul>', verbose_name='Fulfillment of Problem')),
                ('engineering_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DanceElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Storyline or concept of dance incorporates a technological advancement but makes an unclear statement about its effects.</li>\n<li>Music or props, rather than dance elements, tell a majority of the story.</li>\n<li>One prop/costume/set item is not made by students.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DanceMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Storyline or concept of dance incorporates a technological advancement but makes an unclear statement about its effects.</li>\n<li>Music or props, rather than dance elements, tell a majority of the story.</li>\n<li>One prop/costume/set item is not made by students.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='DebateMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('respect_for_other_team', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Most statements and responses were respectful and in appropriate language, but there was one sarcastic remark</li></ul>')),
                ('information', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Most information presented in the debate was clear and accurate, but was not usually thorough</li></ul>')),
                ('rebutal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Most counter-arguments were accurate and relevant, but several were weak.</li></ul>')),
                ('use_of_facts_statistics', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Every major point was supported with facts, statistics and/or examples, but the relevance of some was questionable.</li></ul>', verbose_name='Use of Facts/Statistics')),
                ('organization', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Most counter-arguments were accurate and relevant, but several were weak.</li></ul>')),
                ('understanding_of_topic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The team seemed to understand the main points of the topic and presented those with ease.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='EngElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Presentation demonstrates understanding of the material.</li>\n<li>Presenters facilitate engaging discussion regarding challenge expectations</li>\n<li>Presenters explain their research concerning the shoe  as it relates to environmental sustainability.</li>\n<li>The  purpose of the design is clear, realistic, and share how production may be scaled up.</li>\n<li>Most students have an explicit part in either the explanation or demonstration of the design process regarding the prototype ; however, one or two may function as support.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('engineering_design_prototype_working_model', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The operation and design of the prototype somewhat fulfill the challenge, but is unclear in some aspects.</li></ul>', verbose_name='Engineering Design/Prototype/Working Model')),
                ('engineering_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='EngMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Presentation demonstrates understanding of the material.</li>\n<li>Presenters facilitate engaging discussion regarding challenge expectations.</li>\n<li>Presenters explain their research concerning the CO2 device as it relates to environmental sustainability.</li>\n<li>The purpose of the design is clear, realistic, and presenters share how it may be scaled up.</li>\n<li>Most students have an explicit part in either the explanation or demonstration of the design process regarding the prototype; however, one or two may function as support.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('engineering_design_prototype_working_model', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The operation and design of the prototype somewhat fulfill the challenge, but is unclear in some aspects.</li></ul>', verbose_name='Engineering Design/Prototype/Working Model')),
                ('engineering_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='RocketMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The vehicle includes propulsion, payload and recovery systems.</li>\n<li>The bottom bottle is not damaged in any way.</li>\n<li>The fins are not lower than where the bottle begins.</li>\n<li>The rocket launches as one complete unit.</li>\n<li>The rocket flies mostly straight</li>\n<li>One aesthetic aspect of the rocket does not function to aid the launch.</li>\n<li>The payload is delivered with superficial damage.</li>\n<li>Most students have an explicit part in either the launching or explanation of the design process; however, one or two may function as support.</li></ul>')),
                ('engineering_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Written statement submitted at the time of performance.</li>\n<li>Statement is neat and has 1-3 spelling/grammatical/punctuation errors.</li>\n<li>Statement links standards to key elements and outcome, but may be unclear in one or two places.</li></ul>')),
                ('fulfillment_of_problem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>The execution of the launching and the design of the rocket fulfill all but 1 challenge requirement.</li>\n<li>The distance from the middle of the payload’s final destination to the middle of the target is greater than 60.96cm but less than 120 cm.</li></ul>', verbose_name='Fulfillment of Problem')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='SpokenElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>All team members have explicit roles in the performance, but one or more have notably lesser roles.</li>\n<li>Eye contact is made and maintained with the audience with some breaks in the performance.</li>\n<li>No reading of notes.</li>\n<li>Verbal cues such as tone, pace, volume and intended pauses are used and further the impact, but some may be ineffective.</li>\n<li>Non verbal cues such as gestures, facial expressions and body language are used and further the impact but some may be ineffective.</li>\n<li>Speakers exude positive energy and use animated speech.</li>\n<li>The performance somewhat fulfills the challenge, but is unclear in some aspects.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
                ('poem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Poem includes language that promotes vivid images that contribute to the poem</li>\n<li>The poem does address the issue at hand.</li>\n<li>The poem has less than 2 grammatical errors.</li>\n<li>The poem is somewhat impactful piece.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='SpokenMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>All team members have explicit roles in the performance, but one or more have notably lesser roles.</li>\n<li>Eye contact is made and maintained with the audience with some breaks in the performance.</li>\n<li>No reading of notes.</li>\n<li>Verbal cues such as tone, pace, volume and intended pauses are used and further the impact; most are effective.</li>\n<li>Non verbal cues such as gestures, facial expressions and body language are used and further the impact but some may be ineffective.</li>\n<li>Speakers exude positive energy and use animated speech.</li>\n<li>The performance somewhat fulfills the challenge, but is unclear in some aspects.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
                ('poem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Poem includes language that promotes vivid images that contribute to the poem</li>\n<li>The poem does address the issue at hand.</li>\n<li>The poem has less than 2  grammatical errors.</li>\n<li>The poem is somewhat impactful piece.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='Spont',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('specific_to_spontaneous', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Words about things.</li>\n<li>This also says this.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='TheaterElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>One prop/costume/set item is not originally made by students.</li>\n<li>Presentation easily heard or understood by audience.</li>\n<li>Presentation mostly fulfills the challenge.</li>\n<li>Time limit exceeded by &gt; 30 s.</li>\n<li>Most students maintained character throughout the play, even when not speaking.</li>\n<li>Most students have an explicit part in the acting and support.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='TheaterMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>One prop/costume/set item is not originally made by students.</li>\n<li>Presentation easily heard or understood by audience.</li>\n<li>Presentation mostly fulfills the challenge.</li>\n<li>Time limit exceeded by &gt; 30 s.</li>\n<li>Most students maintained character throughout the play, even when not speaking.</li>\n<li>Most students have an explicit part in the acting and support.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='VisualArtsElem',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Presentation clarity (Clear message, some eye contact, appropriate responses, and a suitable presentation standard).</li>\n<li>Some research is observable during the presentation.</li>\n<li>All but one team member are present OR all are present and one member does not participate.</li></ul>')),
                ('artwork', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Artwork identifies one technology impact.</li>\n<li>Artwork illustrates some contrived positive and negative impacts.</li>\n<li>Artwork reflects thorough examination of the topic.</li>\n<li>Artwork develops visual imagery.</li>\n<li>Artwork demonstrates unity of thought, imagery, form, media and techniques in support of creative intent.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.CreateModel(
            name='VisualArtsMiddle',
            fields=[
                ('shared_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steamify.Shared')),
                ('presentation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Presentation clarity (Clear message, some eye contact, appropriate responses, and a suitable presentation standard).</li>\n<li>Some research is observable during the presentation.</li>\n<li>All but one team member are present OR all are present and one member does not participate.</li></ul>')),
                ('artwork', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Artwork identifies obvious technology impacts for each year.</li>\n<li>Artwork illustrates some contrived positive and negative impacts.</li>\n<li>Artwork reflects thorough examination of the topic.</li>\n<li>Artwork develops visual imagery.</li>\n<li>Artwork demonstrates unity of thought, imagery, form, media and techniques in support of creative intent.</li></ul>')),
                ('design_notebook', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Relevant research from more than 3 different reputable resources is included and documented in the design notebook in “Resources” section.</li>\n<li>Design process somewhat chronicled.</li>\n<li>Design notebook quality is at standard (Table of contents is inaccurate, page numbers are mostly correct, titles and dates are somewhat clear, entries and figures are clear).</li></ul>')),
                ('artist_statement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='<ul><li>Statement is neat and has less than two spelling/grammatical/punctuation errors.</li>\n<li>Statement includes standards and key elements</li>\n<li>How some standards/elements fit into story outcome is somewhat unclear.</li>\n<li>Statement includes description of team work, but each member’s role is not clear.</li></ul>')),
            ],
            bases=('steamify.shared',),
        ),
        migrations.AddField(
            model_name='shared',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamify.Team'),
        ),
    ]
