# Generated by Django 2.2.4 on 2019-10-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steamify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spont',
            name='specific_to_spontaneous',
        ),
        migrations.AddField(
            model_name='spont',
            name='focus_on_the_task',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='\n        <ul>\n            <li>Almost all team members (one person did not fulfill one of the following):\n                <ul>\n                    <li>Stay on task all of the time without reminders.</li>\n                    <li>Work hard and helps others in the group.</li>\n                    <li>Gather information and shares useful ideas for discussions.</li>\n                </ul>\n            </li>\n        </ul>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spont',
            name='listening_questioning_discussing',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='<ul><li>Respectfully listens, discusses and asks questions.</li></ul>', verbose_name='Listening, questioning, discussing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spont',
            name='success_in_problem_resolution',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='<ul><li>The problem was almost resolved.</li></ul>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spont',
            name='teamwork',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='\n        <ul><li>Almost all team members (one person did not fulfill one of the following):\n            <ul>\n                <li>Contributed equally to the finished project.</li>\n                <li>Worked until the end of the task.</li>\n                <li>Actively seek and suggest solutions to problems.</li>\n            </ul>\n        </li></ul>\n        '),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AllowedDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
